apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: java-server
    app.kubernetes.io/instance: java-server
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: java-server
spec:
  selector:
    app: java-server
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000