apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: java-server
    app.kubernetes.io/instance: java-server
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: java-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
        - image: 188691447767.dkr.ecr.ap-south-1.amazonaws.com/java-server:latest
          imagePullPolicy: Always
          name: java-server
          ports:
            - containerPort: 5000